# Generated by Django 4.2.4 on 2023-08-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for Delivery', 'Out for Delievry'), ('Delivered', 'Deliverred')], max_length=200, null=True),
        ),
    ]
