# Generated by Django 4.2.4 on 2023-08-31 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_cerated',
            new_name='date_created',
        ),
    ]
