# Generated by Django 4.2.4 on 2023-09-06 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for Delivery', 'Out for Delievry'), ('Delivered', 'Delivered')], max_length=1000, null=True),
        ),
    ]
